name: Nawshad Binta Nizam
title: Nawshad Binta Nizam
author: Nawshad Binta Nizam
url: https://NawshadBintaNizam.github.io
#url: https://github.com/NizamNB/NawshadBintaNizam.github.io.git
base: ''

markdown: kramdown
kramdown:
    enable_coderay: false
    auto_ids: false
    entity_output: symbolic
highlighter: rouge

exclude:
    - bower_components
    - node_modules
    - package.json
    - bower.json
    - drafts

navigation:
    - title: About
      link: /index
      name: about
    - title: Statement
      link: /content/Research_Statement.pdf
    - title: Research
      link: /research
    - title: Awards/Honors
      link: /achievements
    - title: Hobbies
      link: hobbies
    - title: CV
      link: /content/K_M_Naimul_Hassan_Resume.pdf

theme: jekyll-theme-minimal

sass:
  sass_dir: _sass
